### ISSUE TITLE
Player broken for new videos.

### ISSUE THREAD

**Issue by jamesmaino** [patrickgalbraith/rageagain#2]
I noticed since the big rageagain update, it has been having issues (particularly) serving new videos (presumably those not in the cache?). 

e.g. 

[https://rageagain.com/#/episode/2021/08/22_night/2](https://rageagain.com/#/episode/2021/08/22_night/2)

Great work on this site! One of my favourite projects.

**Comment by patrickgalbraith** [comment]
Fixed in 88bc927ae7d2d8ef05b9018c062032a5dc35a2db
