### ISSUE TITLE
Missing the last two years

### ISSUE THREAD

**Issue by simonhildebrandt** [patrickgalbraith/rageagain#3]
Hi Patrick, love the project. I noticed that the site's missing 2023 and 2024 - any idea why? Would you be interested in someone trying to prod it back to life?

**Comment by patrickgalbraith** [comment]
Yeah the scraper is broken and I haven't got around to fixing it unfortunately. Scrapers are a bit of a pain in the arse to maintain! But it should be an easy fix.

Feel free to take a crack at it, the code is fairly simple.
